AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Controllers/CatalogoProductServiceController.cs
using DataAccess.Models;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Utiles;

namespace AppDirectorioWeb.Areas.Ventas.Controllers
{
    [Area("Ventas")]
    public class CatalogoProductServiceController : Controller
    {

        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;

        public CatalogoProductServiceController(
             UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            RoleManager<IdentityRole> roleManager,
            IUnitOfWork unitOfWork
            )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            HttpContext.Session.SetString("UserId", _userManager.FindByNameAsync(User.Identity.Name).Result.Id);

            if (_unitOfWork.Business.GetBusinessByIdOwner(HttpContext.Session.GetString("UserId")) != null)
            {
                //temporal hasta que se cambie la funcionalidad y se permitan más negocios por usuario
                var idNegocios = _unitOfWork.Business.GetBusinessByIdOwner(HttpContext.Session.GetString("UserId")).Id;
                HttpContext.Session.SetString("idNegocioUser", idNegocios.ToString());
            }
            else
            {
                HttpContext.Session.SetString("idNegocioUser", "0");
            }

            ViewBag.ExistenCatCinfig = _unitOfWork.CatConfigPordServ.lstConfigCat(Convert.ToInt32(HttpContext.Session.GetString("idNegocioUser"))).Count();
            return View();
        }

        [Authorize(Roles = SP.Role_BusinesAdmin + "," + SP.Role_Admin)]
        public IActionResult AddUpdCatConfig(int? id)
        {
            string ownerId = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;
            ConfigCatalogoViewModel model = new ConfigCatalogoViewModel();
            if (id == null)
            {
            
                model.Id = 0;
                model.Activo = true;
                model.IdNegocio = _unitOfWork.Business.GetBusinessByIdOwner(ownerId).Id;
                model.IdUsuarioCreacion = ownerId;
                model.FechaCreacion = DateTime.Now;
                model.lstTipoPagos = new List<CatTipoPagoXcatalogoConfigViewModel>();
                model.lstTipoPagos = _unitOfWork.CatConfigPordServ.GetLstTipoPagoByIdCatConfig(id);
                return View(model);
            }

            var c = _unitOfWork.CatConfigPordServ.GetConfigCatById(id);

            if (c == null)
            {
                return NotFound();
            }

            model = c;
            model.FechaActualizacion = DateTime.Now;
            model.IdUsuarioActualizacion = ownerId;
            model.lstTipoPagos = _unitOfWork.CatConfigPordServ.GetLstTipoPagoByIdCatConfig(id);
            //ViewBag.CuponActive = _unitOfWork.Cuponera.VerifyActiveCupon(c.IdNegocio);
            return View(model);
           
        }

        [Authorize(Roles = SP.Role_BusinesAdmin + "," + SP.Role_Admin)]
        [HttpPost]
        public IActionResult AddUpdCatConfig(ConfigCatalogoViewModel model)
        {
           
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    //creación
                    ConfigCatalogo nCatConfig = new ConfigCatalogo
                    {
                        Id = model.Id,
                        IdMoneda = (int)model.IdMoneda,
                        IdNegocio = model.IdNegocio,
                        IdTipoCatalogo = model.IdTipoCatalogo,
                        IdUsuarioCreacion = model.IdUsuarioCreacion,
                        FechaCreacion = model.FechaCreacion,
                        NombreCatalogo = model.NombreCatalogo,
                        DescuentoMasivo = model.DescuentoMasivo,
                        PorcentajeDescuentoMasivo = model.PorcentajeDescuentoMasivo,
                        Activo = model.Activo,

                    };

                   _unitOfWork.CatConfigPordServ.Add(nCatConfig);

                    _unitOfWork.Save();

                    foreach (var item in model.lstTipoPagos)
                    {
                        _unitOfWork.TipoPagoXcatConfig.Add(new CatTipoPagoXcatalogoConfig
                        {
                            IdCatConfigProdServ= nCatConfig.Id,
                            IdTipoPago=item.IdTipoPago,
                            Active=item.Active
                        });

                        _unitOfWork.Save();
                    }
                }
                else
                {
                   
                    //update
                    _unitOfWork.CatConfigPordServ.UpdateCatConfig(new ConfigCatalogo
                    {
                        Id = model.Id,
                        IdMoneda = (int)model.IdMoneda,
                        IdNegocio = model.IdNegocio,
                        IdTipoCatalogo = model.IdTipoCatalogo,
                        IdUsuarioCreacion = model.IdUsuarioCreacion,
                        FechaCreacion = model.FechaCreacion,
                        NombreCatalogo = model.NombreCatalogo,
                        DescuentoMasivo = model.DescuentoMasivo,
                        PorcentajeDescuentoMasivo = model.PorcentajeDescuentoMasivo,
                        Activo = model.Activo,
                    });

                    foreach (var item in model.lstTipoPagos)
                    {
                        _unitOfWork.TipoPagoXcatConfig.Update(new CatTipoPagoXcatalogoConfig
                        {

                            Active = item.Active,
                            Id=item.Id

                        }) ;

                        _unitOfWork.Save();
                    }


                }

                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult GetLstConfigCat()
        {
            //aqui quede. falta agregar los tipos de pago al lstConfigCat y probar que guarda, edita y carga los datos.luego probar validaciones
            //y resto de boton editar OJO
            int? idNegocio = null;
            //verificar que tipo de usuario esta consultabdo esto
            //hacer logica para traer los cupones, lgica para bussinesAdmin y Admin site
            if (User.IsInRole(SP.Role_BusinesAdmin))
            {
               
                HttpContext.Session.SetString("UserId", _userManager.FindByNameAsync(User.Identity.Name).Result.Id);

                if (_unitOfWork.Business.GetBusinessByIdOwner(HttpContext.Session.GetString("UserId")) != null)
                {
                    //temporal hasta que se cambie la funcionalidad y se permitan más negocios por usuario
                    var idNegocios = _unitOfWork.Business.GetBusinessByIdOwner(HttpContext.Session.GetString("UserId")).Id;
                    HttpContext.Session.SetString("idNegocioUser", idNegocios.ToString());
                }
                else
                {
                    HttpContext.Session.SetString("idNegocioUser", "0");
                }

                idNegocio =Convert.ToInt32(HttpContext.Session.GetString("idNegocioUser"));
            }

            var configCat = _unitOfWork.CatConfigPordServ.lstConfigCat(idNegocio);

            foreach (var item in configCat)
            {
                item.NombreTipoPagos = _unitOfWork.CatConfigPordServ.GetStringNamesTipoPago(item.Id);
            }

            return Json(new { data = configCat });
        }
    }
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/CatalogoProductService/AddUpdCatConfig.cshtml
@model Models.ViewModels.ConfigCatalogoViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = "Crear Config Catalogo";
}

<section class="py-7 py-md-10 bg-light height100vh">
    <div class="container">
        <div class="border p-6 p-lg-9 bg-white">
            <div class="row">
                <div class="col-md-6 col-xs-12 pr-md-6 pr-lg-9">
                    <form  asp-action="AddUpdCatConfig" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdNegocio" />
                        <input type="hidden" asp-for="Id" />
                        @if (Model.Id != 0)
                        {
                            title = "Actualizar Config Catalogo";
                        }
                        <h2 class="h3 mb-6">@title</h2>
                        <input asp-for="IdUsuarioCreacion" type="hidden" />
                        <input asp-for="IdNegocio" type="hidden" />
                        <input asp-for="FechaCreacion" type="hidden" />
                        <input asp-for="IdUsuarioActualizacion" type="hidden" />
                        <input asp-for="FechaActualizacion" type="hidden" />
                        <div class="form-group mb-6">
                            <label asp-for="NombreCatalogo"></label>
                            <input asp-for="NombreCatalogo" type="text" class="form-control border" placeholder="Nombre Catalogo">
                            <span asp-validation-for="NombreCatalogo" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-6">
                            <label>Tipo Catalogo</label>
                            <select id="cboIdTipoCat" class="form-control">
                                <option>-- Seleccione un tipo --</option>
                                <option value="1">Productos</option>
                                <option value="2">Servicios</option>

                            </select>
                            <span asp-validation-for="IdTipoCatalogo" class="text-danger"></span>
                            <input asp-for="IdTipoCatalogo" type="hidden" />

                        </div>
                        <div class="form-group mb-6">
                            <label>Tipo Móneda</label>
                            <select id="cboIdMoneda" class="form-control">
                                <option>-- Seleccione una móneda --</option>
                                <option value="1">(C$) Córdobas</option>
                                <option value="2">($) Dólares</option>

                            </select>
                            <span asp-validation-for="IdMoneda" class="text-danger"></span>
                            <input asp-for="IdMoneda" type="hidden" />

                        </div>
                        <div class="form-group mb-6">
                            <div class="form-check">

                                <input asp-for="DescuentoMasivo" class="form-check-input" type="checkbox" id="chkboxDescMasivo">
                                <label class="form-check-label" for="gridCheck">
                                    Aplicar descuento másivo?

                                </label>
                            </div>
                        </div>
                        <div id="divMtoDctoMasivo" class="form-group mb-6">
                            <label asp-for="PorcentajeDescuentoMasivo"></label>
                            <input asp-for="PorcentajeDescuentoMasivo" type="text" class="form-control border" placeholder="Porcentaje de descuento">
                            <span asp-validation-for="PorcentajeDescuentoMasivo" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-6">
                            <label>Tipo de pagos aceptados</label>
                            <br />
                            <div class="form-check">

                                @for (int i = 0; i < Model.lstTipoPagos.Count; i++)
                                {

                                    <input type="hidden" asp-for="@Model.lstTipoPagos[i].Id" />
                                    <input type="hidden" asp-for="@Model.lstTipoPagos[i].IdCatConfigProdServ" />
                                    <input type="hidden" asp-for="@Model.lstTipoPagos[i].IdTipoPago" />
                                    <input asp-for="@Model.lstTipoPagos[i].Active" type="checkbox" class="form-check-input">
                                    <label class="form-check-label" for="gridCheck">@Model.lstTipoPagos[i].NombreTipoPago</label><br />
                                }

                            </div>
                        </div>

                        <div class="form-group mb-6">
                            <div class="form-check">

                                <input asp-for="Activo" class="form-check-input" type="checkbox" id="chkboxActivo">
                                <label class="form-check-label" for="gridCheck">
                                    Activo

                                </label>
                            </div>
                        </div>

                        <div class="form-group mb-0">
                            @if (Model.Id != 0)
                            {
                                @*if (ViewBag.CuponActive == true && Model.Status == true)
                {
                    <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Actualizar</button>
                }
                else if (ViewBag.CuponActive == false && Model.Status == false)
                {
                    <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Actualizar</button>
                }
                else
                {
                    <button type="submit" class="btn btn-primary text-uppercase py-2 px-4" disabled>Actualizar</button>
                }*@
                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Actualizar</button>

                            }
                            else
                            {
                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Guardar</button>
                            }

                            <a asp-area="Ventas" asp-action="Index" asp-controller="CatalogoProductService" class="btn btn-warning text-white text-uppercase py-2 px-4">Regresar</a>
                        </div>

                        <hr class="my-7 d-md-none">
                    </form>
                </div>


            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/Handlers/addUptCatConfigHandler.js"></script>
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/CatalogoProductService/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="bg-light pb-8 pt-5 height100vh">
    <div class="container">
        <!-- Breadcrumb -->
        <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
            <h3 class="font-weight-normal mb-4 mb-md-0">Administración de Cátalogos de productos/servicios</h3>
            @if (ViewBag.ExistenCatCinfig == 0)
            {
                <a asp-area="Ventas" asp-controller="CatalogoProductService" asp-action="AddUpdCatConfig" id="btnCrear" class="btn btn-primary text-white"><i class="fa fa-plus"></i> Agregar Cat Config</a>


            }


        </nav>


        <div id="my-listing_wrapper" class="dataTables_wrapper no-footer">
            <table id="tblCupon" class="  cell-border  table-data-default dataTable no-footer dtr-inline" style="width: 100%;" role="grid">
                <thead>
                    <tr class="table-row-bg-white" role="row">
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Nombre Cátalogo</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Moneda</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Tipo de catalogo</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Tipo de pago</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Descuento másivo</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">% Descuento másivo</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Activo</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
            @*<div class="dataTables_paginate paging_simple_numbers" id="my-listing_paginate">
                    <a class="paginate_button previous disabled" aria-controls="my-listing" data-dt-idx="0" tabindex="0" id="my-listing_previous">Prev</a><span><a class="paginate_button current" aria-controls="my-listing" data-dt-idx="1" tabindex="0">1</a></span><a class="paginate_button next disabled" aria-controls="my-listing" data-dt-idx="2" tabindex="0" id="my-listing_next">Next</a>
                </div>*@
        </div>

    </div>
</section>

@section scripts{
   <script src="~/js/Handlers/configCatHandler.js"></script>
}