AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Controllers/ItemCatalogoProdServController.cs
using DataAccess.Models;
using DataAccess.Repository.IRepository;
using Firebase.Auth;
using Firebase.Storage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Utiles;

namespace AppDirectorioWeb.Areas.Ventas.Controllers
{
    [Area("Ventas")]
    public class ItemCatalogoProdServController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;

        public ItemCatalogoProdServController(
             UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            RoleManager<IdentityRole> roleManager,
            IUnitOfWork unitOfWork
            )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _unitOfWork = unitOfWork;
        }
        [Authorize]
        public IActionResult Index(int idConfigCat)
        {
         

            if (idConfigCat==0)
            {
                ViewBag.idConfigCat = HttpContext.Session.GetString("idConfigCat");
            }
            else
            {
                ViewBag.idConfigCat = idConfigCat;

                HttpContext.Session.SetString("idConfigCat", idConfigCat.ToString());
            }

            return View();
        }

        public IActionResult SeeCatProd(int idConfigCat)
        {
            //revisar descuento y mejorar UI
            List<ItemCatalogoViewModel> model = new List<ItemCatalogoViewModel>();
            model = _unitOfWork.ItemCatalogo.GetItemsCatalogoForBueyrs(idConfigCat);
            return View(model);
        }


        [Authorize(Roles = SP.Role_BusinesAdmin + "," + SP.Role_Admin)]
        public IActionResult AddUpdItemCat(int? id)
        {
         
            ItemCatalogoViewModel model = new ItemCatalogoViewModel();
            if (id == null)
            {

                model.Id = 0;
                model.Activo = true;
                model.IdConfigCatalogo = Convert.ToInt32(HttpContext.Session.GetString("idConfigCat"));

                model.Categories = _unitOfWork.Category.GetAll().Where(x => x.IdPadre == 43 && x.Activo == true).Select(x => new { x.Id, x.Nombre }).Select(i => new SelectListItem
                {
                    Text = i.Nombre,
                    Value = i.Id.ToString()
                });

                return View(model);
            }

            var c = _unitOfWork.ItemCatalogo.GetItemCatalogoById((int)id);

            if (c == null)
            {
                return NotFound();
            }

            model = c;
            model.Categories = _unitOfWork.Category.GetAll().Where(x => x.IdPadre == 43 && x.Activo == true).Select(x => new { x.Id, x.Nombre }).Select(i => new SelectListItem
            {
                Text = i.Nombre,
                Value = i.Id.ToString()
            });
            //ViewBag.CuponActive = _unitOfWork.Cuponera.VerifyActiveCupon(c.IdNegocio);
            return View(model);

        }



        [Authorize(Roles = SP.Role_BusinesAdmin + "," + SP.Role_Admin)]
        public IActionResult GetDetailsRead(int? id)
        {

            ItemCatalogoViewModel model = new ItemCatalogoViewModel();
           

            var c = _unitOfWork.ItemCatalogo.GetItemCatalogoById((int)id);

            if (c == null)
            {
                return NotFound();
            }

            model = c;
            model.Categories = _unitOfWork.Category.GetAll().Where(x => x.IdPadre == 43 && x.Activo == true).Select(x => new { x.Id, x.Nombre }).Select(i => new SelectListItem
            {
                Text = i.Nombre,
                Value = i.Id.ToString()
            });
            //ViewBag.CuponActive = _unitOfWork.Cuponera.VerifyActiveCupon(c.IdNegocio);
            return View(model);

        }


        [Authorize(Roles = SP.Role_BusinesAdmin + "," + SP.Role_Admin)]
        [HttpPost]
        public IActionResult AddUpdItemCat(ItemCatalogoViewModel model)
        {
           
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    //creación
                    _unitOfWork.ItemCatalogo.Add(new ItemCatalogo
                    {
                        IdCategoriaItem=model.IdCategoriaItem,
                        IdConfigCatalogo=model.IdConfigCatalogo,
                        IdUsuarioCreacion = HttpContext.Session.GetString("UserId"),
                        NombreItem=model.NombreItem,
                        DescripcionItem=model.DescripcionItem,
                        PrecioUnitario=model.PrecioUnitario,
                        TieneDescuento=model.TieneDescuento,
                        PorcentajeDescuento=model.PorcentajeDescuento,
                        FechaCreacion=DateTime.Now,
                        Activo=model.Activo,
                        ImagenItem= SaveItemPicture(model).Result,

                    });
                }
                else
                {
                    var imageStateActual = _unitOfWork.ItemCatalogo.Get(model.Id).ImagenItem;
                    //update
                    _unitOfWork.ItemCatalogo.Update(new ItemCatalogo
                    {
                        Id = model.Id,
                        IdCategoriaItem = model.IdCategoriaItem,
                        IdConfigCatalogo = model.IdConfigCatalogo,
                        NombreItem = model.NombreItem,
                        DescripcionItem = model.DescripcionItem,
                        PrecioUnitario = model.PrecioUnitario,
                        TieneDescuento = model.TieneDescuento,
                        PorcentajeDescuento = model.PorcentajeDescuento,
                        Activo = model.Activo,
                        ImagenItem = (model.PictureItem != null && model.PictureItem.Length > 0) ? SaveItemPicture(model).Result : imageStateActual,
                        FechaActualizacion = DateTime.Now,
                        IdUsuarioActualizacion = HttpContext.Session.GetString("UserId")
                    });
                }

                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            model.Categories = _unitOfWork.Category.GetAll().Where(x => x.IdPadre == 43 && x.Activo == true).Select(x => new { x.Id, x.Nombre }).Select(i => new SelectListItem
            {
                Text = i.Nombre,
                Value = i.Id.ToString()
            });
            return View(model);
        }

        [HttpGet]
        public IActionResult GetItemsCat(int idConfigCat)
        {
            var ItemsCat = _unitOfWork.ItemCatalogo.GetItemsCatalogo(idConfigCat);

            return Json(new { data = ItemsCat });
        }

        public async Task<string> SaveItemPicture(ItemCatalogoViewModel model)
        {
            string uniqueFileName = "";
            try
            {

                if (model.PictureItem != null && model.PictureItem.Length > 0)
                {

                    uniqueFileName = Guid.NewGuid().ToString() + model.PictureItem.FileName;

                    Stream stream = model.PictureItem.OpenReadStream();
                    //firebase logic to upload file
                    var auth = new FirebaseAuthProvider(new FirebaseConfig(FirebaseSetting.ApiKey));
                    var a = await auth.SignInWithEmailAndPasswordAsync(FirebaseSetting.AuthEmail, FirebaseSetting.AuthPassword);


                    //cancellation token
                    var cancellation = new CancellationTokenSource();

                    var upload = new FirebaseStorage(
                        FirebaseSetting.Bucket,
                        new FirebaseStorageOptions
                        {
                            AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken),
                            ThrowOnCancel = true

                        }
                        ).Child("businessCatalog")
                        .Child($"{uniqueFileName}")
                        .PutAsync(stream, cancellation.Token);



                    uniqueFileName = await upload;

                }

            }
            catch (Exception ex)
            {

                throw;
            }



            return uniqueFileName;
        }


        [HttpGet]
        [Authorize(Roles = SP.Role_BusinesAdmin + "," + SP.Role_Admin)]
        public async Task<IActionResult> DeleteItemPic(int id)
        {
            var Item = _unitOfWork.ItemCatalogo.Get(id);
            if (Item == null)
            {
                return Json(new { success = false, message = "Error al borrar" });
            }

            //firebase logic


            try
            {
                string fileName = Item.ImagenItem.Replace("https://firebasestorage.googleapis.com/v0/b/brujulapyme-1bb75.appspot.com/o/businessCatalog%2F", "");


                fileName = fileName.Substring(0, fileName.IndexOf('?'));
                var auth = new FirebaseAuthProvider(new FirebaseConfig(FirebaseSetting.ApiKey));
                var a = await auth.SignInWithEmailAndPasswordAsync(FirebaseSetting.AuthEmail, FirebaseSetting.AuthPassword);

                //cancellation token
                var cancellation = new CancellationTokenSource();

                var del = new FirebaseStorage(
                    FirebaseSetting.Bucket,
                    new FirebaseStorageOptions
                    {

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/ItemCatalogoProdServ/AddUpdItemCat.cshtml
@model Models.ViewModels.ItemCatalogoViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = "Agregar producto/servicio";
}

<section class="py-7 py-md-10 bg-light height100vh">
    <div class="container">
        <div class="border p-6 p-lg-9 bg-white">
            <div class="row">
                <div class="col-md-6 col-xs-12 pr-md-6 pr-lg-9">
                    <form enctype="multipart/form-data" asp-action="AddUpdItemCat" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdConfigCatalogo" />
                        <input type="hidden" asp-for="Id" />
                        @if (Model.Id != 0)
                        {
                            title = "Actualizar producto/servicio";
                        }
                        <h2 class="h3 mb-6">@title</h2>
                        <div class="form-group mb-6">
                            <label asp-for="NombreItem"></label>
                            <input asp-for="NombreItem" type="text" class="form-control border" placeholder="Nombre producto/servicio">
                            <span asp-validation-for="NombreItem" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-6">
                            <label for="discribeTheListing">Descripción del producto/servicio</label>
                            <textarea asp-for="DescripcionItem" class="form-control" rows="8" required></textarea>
                            <span asp-validation-for="DescripcionItem" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-6">
                            <label for="exampleFormControlSelect1">Departamento</label>
                            <div class="select-default bg-white">
                                @Html.DropDownListFor(m => m.IdCategoriaItem, Model.Categories, "- SELECCIONA UNA CATEGORIA -", new { @class = "form-control " })
                                <span asp-validation-for="IdCategoriaItem" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group mb-6">
                            <div class="form-check">

                                <input asp-for="TieneDescuento" class="form-check-input" type="checkbox" id="chkboxDescMasivo">
                                <label class="form-check-label" for="gridCheck">
                                    Tiene descuento?

                                </label>
                            </div>
                        </div>
                        <div id="divMtoDctoMasivo" class="form-group mb-6">
                            <label asp-for="PorcentajeDescuento"></label>
                            <input asp-for="PorcentajeDescuento" type="text" class="form-control border" placeholder="Porcentaje de descuento">
                            <span asp-validation-for="PorcentajeDescuento" class="text-danger"></span>
                        </div>


                        <div class="form-group mb-6">
                            <label asp-for="PrecioUnitario"></label>
                            <input asp-for="PrecioUnitario" class="form-control border" placeholder="Precio">
                            <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
                        </div>

                        <input type="hidden" asp-for="ImagenItem" />
                        @if (Model.Id != 0 && !string.IsNullOrEmpty(Model.ImagenItem))
                        {
                            <a id="adelpiccupon" onclick="DeleteItemPic(@Model.Id)" class="text-danger">@Model.ImagenItem  Eliminar <span class="fa fa-close"></span></a>

                            <div class="form-group col-md-12">
                                <input accept="image/*" asp-for="PictureItem" class="form-control custom-file-input cfi cfiinvisible">
                                <label class="custom-file-label cfl">Selecciona imagen para el producto/servicio...</label>
                                <span class="text-danger field-validation-error"><span id="picVal" class=""></span></span>
                            </div>
                        }
                        else
                        {
                            <div class="form-group col-md-12">
                                <input accept="image/*" asp-for="PictureItem" class="form-control custom-file-input cfi">
                                <label class="custom-file-label cfl">Selecciona imagen para el producto/servicio...</label>
                                <span class="text-danger field-validation-error"><span id="picVal" class=""></span></span>
                            </div>
                        }



                        <div class="form-group mb-6">
                            <div class="form-check">

                                <input asp-for="Activo" class="form-check-input" type="checkbox" id="chkboxActivo">
                                <label class="form-check-label" for="gridCheck">
                                    Disponible

                                </label>
                            </div>
                        </div>



                        <div class="form-group mb-0">
                            @if (Model.Id != 0)
                            {

                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Actualizar</button>


                            }
                            else
                            {
                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Guardar</button>
                            }

                            <a asp-area="Ventas" asp-action="Index" asp-controller="ItemCatalogoProdServ" class="btn btn-warning text-white text-uppercase py-2 px-4">Regresar</a>
                        </div>

                        <hr class="my-7 d-md-none">
                    </form>
                </div>


            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/Handlers/AddUpdtItemCatHandler.js"></script>
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/ItemCatalogoProdServ/GetDetailsRead.cshtml
@model Models.ViewModels.ItemCatalogoViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = "Detalle producto/servicio";
}

<section class="py-7 py-md-10 bg-light height100vh">
    <div class="container">
        <div class="border p-6 p-lg-9 bg-white">
            <div class="row">
                <div class="col-md-6 col-xs-12 pr-md-6 pr-lg-9">
                    <form enctype="multipart/form-data" >
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdConfigCatalogo" />
                        <input type="hidden" asp-for="Id" />
                     
                        <h2 class="h3 mb-6">@title</h2>
                        <div class="form-group mb-6">
                            <label asp-for="NombreItem"></label>
                            <input asp-for="NombreItem" type="text" class="form-control border" placeholder="Nombre producto/servicio" >
                            <span asp-validation-for="NombreItem" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-6">
                            <label for="discribeTheListing">Descripción del producto/servicio</label>
                            <textarea asp-for="DescripcionItem" class="form-control" rows="8" required></textarea>
                            <span asp-validation-for="DescripcionItem" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-6">
                            <label for="exampleFormControlSelect1">Departamento</label>
                            <div class="select-default bg-white">
                                @Html.DropDownListFor(m => m.IdCategoriaItem, Model.Categories, "- SELECCIONA UNA CATEGORIA -", new { @class = "form-control " })
                                <span asp-validation-for="IdCategoriaItem" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group mb-6">
                            <div class="form-check">

                                <input asp-for="TieneDescuento" class="form-check-input" type="checkbox" id="chkboxDescMasivo">
                                <label class="form-check-label" for="gridCheck">
                                    Tiene descuento?

                                </label>
                            </div>
                        </div>
                        <div id="divMtoDctoMasivo" class="form-group mb-6">
                            <label asp-for="PorcentajeDescuento"></label>
                            <input asp-for="PorcentajeDescuento" type="text" class="form-control border" placeholder="Porcentaje de descuento">
                            <span asp-validation-for="PorcentajeDescuento" class="text-danger"></span>
                        </div>


                        <div class="form-group mb-6">
                            <label asp-for="PrecioUnitario"></label>
                            <input asp-for="PrecioUnitario" class="form-control border" placeholder="Precio">
                            <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
                        </div>

                        <input type="hidden" asp-for="ImagenItem" />
                        <div class="form-group mb-6">
                            <img src="@Model.ImagenItem"/>
                        </div>



                        <div class="form-group mb-6">
                            <div class="form-check">

                                <input asp-for="Activo" class="form-check-input" type="checkbox" id="chkboxActivo">
                                <label class="form-check-label" for="gridCheck">
                                    Disponible

                                </label>
                            </div>
                        </div>



                        <div class="form-group mb-0">


                            <a asp-area="Ventas" asp-action="Index" asp-controller="ItemCatalogoProdServ" class="btn btn-warning text-white text-uppercase py-2 px-4">Regresar</a>
                        </div>

                        <hr class="my-7 d-md-none">
                    </form>
                </div>


            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/Handlers/AddUpdtItemCatHandler.js"></script>
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/ItemCatalogoProdServ/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="bg-light pb-8 pt-5 height100vh">
    <div class="container">
        <!-- Breadcrumb -->
        <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
            <h3 class="font-weight-normal mb-4 mb-md-0">Administración de Productos/Servicios</h3>
            <input id="idConfigCat" type="hidden" value="@ViewBag.idConfigCat" />

            <a asp-area="Ventas" asp-controller="ItemCatalogoProdServ" asp-action="AddUpdItemCat" id="btnCrear" class="btn btn-primary text-white"><i class="fa fa-plus"></i>Agregar nuevo producto/servicio</a>

            <a asp-area="Ventas" asp-controller="CatalogoProductService" asp-action="Index" class="btn btn-success text-white"><i class="fa fa-plus"></i>Regresar</a>

        </nav>


        <div id="my-listing_wrapper" class="dataTables_wrapper no-footer">
            <table id="tblItems" class="  cell-border  table-data-default dataTable no-footer dtr-inline" style="width: 100%;" role="grid">
                <thead>
                    <tr class="table-row-bg-white" role="row">
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">#Codigo Item</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Nombre producto/servicio</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Tiene descuento</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Valor descuento (%)</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Moneda</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Precio Unitario</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Disponible</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
            @*<div class="dataTables_paginate paging_simple_numbers" id="my-listing_paginate">
                    <a class="paginate_button previous disabled" aria-controls="my-listing" data-dt-idx="0" tabindex="0" id="my-listing_previous">Prev</a><span><a class="paginate_button current" aria-controls="my-listing" data-dt-idx="1" tabindex="0">1</a></span><a class="paginate_button next disabled" aria-controls="my-listing" data-dt-idx="2" tabindex="0" id="my-listing_next">Next</a>
                </div>*@
        </div>

    </div>
</section>

@section scripts{
    <script src="~/js/Handlers/ItemsCatalogoHandler.js"></script>
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/ItemCatalogoProdServ/SeeCatProd.cshtml
@model List<Models.ViewModels.ItemCatalogoViewModel>


<section class="bg-light pb-8 pt-5 height100vh">
    <div class="row">
        @foreach (var item in Model)
        {
           
                <div class="col-lg-3">
                    <div class="p-2">
                        <div class="col-12  p-1" style="border:1px solid #008cba; border-radius: 5px;">
                            <div class="card" style="border:0px;">
                                <a href="#">
                                    <img src="@item.ImagenItem" class="card-img-top rounded" />
                                </a>

                            </div>
                            <div class="pl-1">
                                <a  href="#">
                                    <p class="card-title h5"><b style="color:#2c3e50">@item.NombreItem</b></p>
                                </a> 
                               
                            </div>
                            <div>
                                @if (item.TieneDescuento == true || item.TieneDescuentoMasivo == true)
                                {
                                    <div style="padding-left:5px;">
                                        <p>Precio: <strike><b class="">@item.PrecioUnitario  @item.NombreMoneda </b></strike></p>
                                    </div>
                                    <div style="padding-left:5px;">
                                        <p style="color:maroon">Precio con descuento del @item.PorcentajeDescuento%: <b class=""><br />@item.PrecioUnitarioConDescuento.ToString("0.00") @item.NombreMoneda</b></p>
                                    </div>
                                }
                                else
                                {
                                    <div style="padding-left:5px;">
                                        <p>Precio: <b class="">@item.PrecioUnitario @item.NombreMoneda</b></p>
                                    </div>
                                }
                       
                   
                                <a href="#add-review" class="btn btn-primary ">Agregar a carrito</a>
                            
                             
                            </div>
                        </div>
                    </div>
                </div>
          
        }

    </div>
</section>