AppDirectorioWeb/AppDirectorioWeb/Areas/Catalogos/Controllers/CatCategoryController.cs
using DataAccess.Models;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.ViewModels;
using System;
using Utiles;

namespace AppDirectorioWeb.Areas.Catalogos.Controllers
{
    [Area("Catalogos")]
    [Authorize(Roles = SP.Role_Admin)]
    public class CatCategoryController : Controller
    {
        #region Private Fields

        private readonly IUnitOfWork _unitOfWork;

        #endregion Private Fields

        #region Public Constructors

        public CatCategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        #endregion Public Constructors

        #region Public Methods

        public IActionResult AddCatChild(int id)
        {
            return View(id);
        }

        [HttpDelete]
        public IActionResult DeleteParentCat(int id)
        {
            var cat = _unitOfWork.Category.Get(id);
            if (cat == null)
            {
                return Json(new { success = false, message = "Error al borrar" });
            }

            _unitOfWork.Category.Remove(id);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Se borro categoría padre exitosamente" });
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            CatCategoryViewModel category = new CatCategoryViewModel();
            if (id == null)
            {
                return View(category);
            }

            var cat = _unitOfWork.Category.Get(id.GetValueOrDefault());

            if (cat == null)
            {
                return NotFound();
            }

            category.Id = cat.Id;
            category.IdPadre = cat.IdPadre;
            category.Nombre = cat.Nombre;
            category.Activo = (cat.Activo != null && cat.Activo != false);

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(CatCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    _unitOfWork.Category.Add(new CatCategorium()
                    {
                        Id = model.Id,
                        IdPadre = 0,
                        Nombre = model.Nombre,
                        Activo = model.Activo,
                        IdUserCreate = HttpContext.Session.GetString("UserId"),
                        CreateDate = DateTime.Now
                    });
                }
                else
                {
                    _unitOfWork.Category.Update(new CatCategorium()
                    {
                        Id = model.Id,
                        IdPadre = 0,
                        Nombre = model.Nombre,
                        Activo = model.Activo,
                        IdUserUpdate = HttpContext.Session.GetString("UserId"),
                        UpdateDate = DateTime.Now
                    });
                }

                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public IActionResult UpsertChild(int? id, int? idPadre)
        {
            CatCategoryViewModel category = new CatCategoryViewModel();

            if (id == null)
            {
                category.IdPadre = idPadre;
                category.Activo = true;
                return View(category);
            }

            var cat = _unitOfWork.Category.Get(id.GetValueOrDefault());

            if (cat == null)
            {
                return NotFound();
            }

            category.Id = cat.Id;
            category.Nombre = cat.Nombre;
            category.IdPadre = cat.IdPadre;
            category.Activo = (cat.Activo != null && cat.Activo != false);

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertChild(CatCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    _unitOfWork.Category.Add(new CatCategorium()
                    {
                        Id = model.Id,
                        IdPadre = model.IdPadre,
                        Nombre = model.Nombre,
                        Activo = model.Activo,
                        IdUserCreate = HttpContext.Session.GetString("UserId"),
                        CreateDate = DateTime.Now
                    });
                }
                else
                {
                    _unitOfWork.Category.Update(new CatCategorium()
                    {
                        Id = model.Id,
                        IdPadre = model.IdPadre,
                        Nombre = model.Nombre,
                        Activo = model.Activo,
                        IdUserUpdate = HttpContext.Session.GetString("UserId"),
                        UpdateDate = DateTime.Now
                    });
                }

                _unitOfWork.Save();
                return RedirectToAction(nameof(AddCatChild), new { id = model.IdPadre });
            }

            return View(model);
        }

        #endregion Public Methods

        #region API_CALLS

        [HttpGet]
        public IActionResult GetAllChildCategory(int idPadre)
        {
            var parentsObj = _unitOfWork.Category.GetAll(x => x.IdPadre == idPadre);
            return Json(new { data = parentsObj });
        }

        [HttpGet]
        public IActionResult GetAllParents()
        {
            var test = _unitOfWork.SP_CALL.List<CatCategoryViewModel>(SP.Proc_GetAllCatTest, null);
            var parentsObj = _unitOfWork.Category.GetAll(x => x.IdPadre == 0);
            return Json(new { data = parentsObj });
        }

        #endregion API_CALLS
    }
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Catalogos/Views/CatCategory/AddCatChild.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="bg-light pb-8 pt-5 height100vh">
    <div class="container">
        <!-- Breadcrumb -->
        <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
            <h3 class="font-weight-normal mb-4 mb-md-0">Administración de Maestro Catalogos hijos</h3>
            <input type="hidden" id="hdfIdPadre" value="@Model"/>
            <a asp-area="Catalogos" asp-route-idPadre="@Model" asp-controller="CatCategory" asp-action="UpsertChild" id="btnCrear" class="btn btn-primary text-white"><i class="fa fa-plus"></i> Agregar categoría</a>
            <a asp-area="Catalogos"  asp-controller="CatCategory" asp-action="Index" id="btnRegresar" class="btn btn-success text-white"><i class="fa fa-plus"></i> Regresar a maestro categoría</a>
        </nav>


        <div id="my-listing_wrapper" class="dataTables_wrapper no-footer">
            <table id="tblCategory" class="  cell-border  table-data-default dataTable no-footer dtr-inline" style="width: 100%;" role="grid">
                <thead>
                    <tr class="table-row-bg-white" role="row">
                        <th class="sorting" tabindex="0" aria-controls="my-listing" rowspan="1" colspan="1" style="width: 100px;" aria-label="Listing: activate to sort column ascending">Categoría Principal</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Status</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views"></th>

                    </tr>
                </thead>

            </table>
         
        </div>

    </div>
</section>

@section scripts{
    <script src="~/js/Handlers/CategoryChildHandler.js"></script>
  
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Catalogos/Views/CatCategory/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="bg-light pb-8 pt-5 height100vh">
    <div class="container">
        <!-- Breadcrumb -->
        <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
            <h3 class="font-weight-normal mb-4 mb-md-0">Administración de Maestro Catalogo</h3>
           
            <a asp-area="Catalogos" asp-controller="CatCategory" asp-action="Upsert" id="btnCrear" class="btn btn-primary text-white"><i class="fa fa-plus"></i> Agregar categoría</a>
         
        </nav>
       
        
        <div id="my-listing_wrapper" class="dataTables_wrapper no-footer">
            <table id="tblCategory" class="  cell-border  table-data-default dataTable no-footer dtr-inline" style="width: 100%;" role="grid">
                <thead>
                <tr class="table-row-bg-white" role="row">
                    <th class="sorting" tabindex="0" aria-controls="my-listing" rowspan="1" colspan="1" style="width: 100px;" aria-label="Listing: activate to sort column ascending">Categoría Principal</th>
                    <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Status</th>
                    <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views"></th>
                    
                </tr>
                </thead>
             
            </table>
         
        </div>

    </div>
</section>

@section scripts{ 
    <script src="~/js/Handlers/CategoryHandler.js"></script>
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Catalogos/Views/CatCategory/Upsert.cshtml
@model Models.ViewModels.CatCategoryViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = "Crear Categoría padre";
}

<section class="py-7 py-md-10 bg-light height100vh">
    <div class="container">
        <div class="border p-6 p-lg-9 bg-white">
            <div class="row">
                <div class="col-md-6 col-xs-12 pr-md-6 pr-lg-9">
                    <form asp-action="Upsert" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        @if (Model.Id != 0)
                        {
                            title = "Actualizar categoría padre";
                        }
                        <h2 class="h3 mb-6">@title</h2>
                        <div class="form-group mb-6">
                            <input asp-for="Nombre" id="txtNombreCatPrincipal" type="text" class="form-control border" placeholder="Nombre categoria" required="">
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>


                        <div class="form-group mb-6">
                            <div class="form-check">
                                <input asp-for="Activo" class="form-check-input" type="checkbox" id="chkboxActivo">
                                <label class="form-check-label" for="gridCheck">
                                    Activo

                                </label>
                            </div>
                        </div>

                        <div class="form-group mb-0">
                            @if (Model.Id != 0)
                            {
                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Actualizar</button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Guardar</button>
                            }

                            <a asp-area="Catalogos" asp-action="Index" asp-controller="CatCategory" class="btn btn-warning text-white text-uppercase py-2 px-4">Regresar</a>
                        </div>

                        <hr class="my-7 d-md-none">
                    </form>
                </div>


            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Catalogos/Views/CatCategory/UpsertChild.cshtml
@model Models.ViewModels.CatCategoryViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = "Crear Categoría hijo";
}


<section class="py-7 py-md-10 bg-light height100vh">
    <div class="container">
        <div class="border p-6 p-lg-9 bg-white">
            <div class="row">
                <div class="col-md-6 col-xs-12 pr-md-6 pr-lg-9">
                    <form asp-action="UpsertChild" method="post">
                        <input type="hidden" asp-for="IdPadre" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        @if (Model.Id != 0)
                        {
                            title = "Actualizar categoría hijo";
                        }
                        <h2 class="h3 mb-6">@title</h2>
                        <div class="form-group mb-6">
                            <input asp-for="Nombre" id="txtNombreCatPrincipal" type="text" class="form-control border" placeholder="Nombre categoria" required="">
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-6">
                            <div class="form-check">
                                <input asp-for="Activo"  class="form-check-input" type="checkbox" id="chkboxActivo">
                                <label class="form-check-label" for="gridCheck">
                                    Activo

                                </label>
                            </div>
                        </div>

                        <div class="form-group mb-0">
                            @if (Model.Id != 0)
                            {
                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Actualizar</button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Guardar</button>
                            }

                            <a asp-area="Catalogos" asp-action="AddCatChild" asp-route-id="@Model.IdPadre" asp-controller="CatCategory" class="btn btn-warning text-white text-uppercase py-2 px-4">Regresar</a>
                        </div>

                        <hr class="my-7 d-md-none">
                    </form>
                </div>


            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}