AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Controllers/FacturacionController.cs
using DataAccess.Models;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Utiles;

namespace AppDirectorioWeb.Areas.Ventas.Controllers
{
    [Area("Ventas")]
    public class FacturacionController : Controller
    {
        private readonly DirectorioOnlineCoreContext _db;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;
        public FacturacionController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, DirectorioOnlineCoreContext db, IEmailSender emailSender)
        {
            _unitOfWork = unitOfWork;
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
            _emailSender = emailSender; 
        }
        // GET: FacturacionController
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = SP.Role_Admin)]
        public IActionResult UpInvoice(int id)
        {
            FacturaViewModel invoice = new FacturaViewModel();
          

            var fac = _unitOfWork.Factura.GetDetailInvoice(id);

            if (fac == null)
            {
                return NotFound();
            }

            invoice.User = fac.User;
            invoice.UserId = fac.UserId;
            invoice.NoAutorizacion = fac.NoAutorizacion;
            invoice.PlanSuscripcion = fac.PlanSuscripcion;
            invoice.IdFactura = fac.IdFactura;
            invoice.IdPlan = fac.IdPlan;
            return View(invoice);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SP.Role_Admin)]
        public IActionResult UpInvoice(FacturaViewModel model)
        {
            if (ModelState.IsValid)
            {

                Factura updFact = new Factura();
                updFact.Id = model.IdFactura;
                updFact.FechaPago = DateTime.Now;
                
                updFact.FacturaPagada = true;
                updFact.FechaActualizacion = DateTime.Now;
                updFact.IdUserUpdate = HttpContext.Session.GetString("UserId");
                updFact.NoAutorizacionPago = model.NoAutorizacion;

                

                updFact.FacturaEnviada = SendInvoiceAsync(updFact).Result;
                _unitOfWork.Factura.Update(updFact);

                UserViewModel userProfile = new UserViewModel();
                userProfile.Id = model.UserId;
                userProfile.IdPlan = model.IdPlan;
                userProfile.PlanExpirationDateD = updFact.FechaPago.Value.AddYears(1);
                _unitOfWork.UserDetail.UpdatePlanSuscripcionUser(userProfile);


                _unitOfWork.Save();


                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<bool> SendInvoiceAsync(Factura updFact)
        {

            try
            {
                FacturaViewModel detailsFactura = new FacturaViewModel();
                detailsFactura = _unitOfWork.Factura.GetDetailInvoice(updFact.Id);

                string MailText = "";
                string returnUrl = null;
                returnUrl ??= Url.Content("~/");


                //aqui quede
                string FilePath = Directory.GetCurrentDirectory() + "\\wwwroot\\EmailTemplates\\html_invoice_email_template.html";
                StreamReader str = new StreamReader(FilePath);
                MailText = str.ReadToEnd();
                str.Close();
                MailText = MailText.Replace("[NumFactura]", detailsFactura.IdFactura.ToString()).Replace("[FechaPago]", updFact.FechaPago.Value.ToShortDateString()).Replace("[PrecioPagado]", detailsFactura.MontoPago).Replace("[NoAutorizacion]", updFact.NoAutorizacionPago).Replace("[PlanDescripcion]", detailsFactura.PlanSuscripcion);



                await _emailSender.SendEmailAsync(detailsFactura.UserEmail, "Factura suscripción Brujula Pyme", MailText);

                return true;
            }
            catch (Exception e)
            {

                return false;
            }
      
        }

        #region API_CALLS
        [HttpGet]
        public IActionResult GetInvoices(string userId)
        {
            List<FacturaViewModel> invoiceList = new List<FacturaViewModel>();
            invoiceList = _unitOfWork.Factura.GetInvoice("");
            return Json(new { data = invoiceList });
        }
        #endregion

    }
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/Facturacion/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="bg-light pb-8 pt-5 height100vh">
    <div class="container">
        <!-- Breadcrumb -->
        <nav class="bg-transparent breadcrumb breadcrumb-2 px-0 mb-5" aria-label="breadcrumb">
            <h3 class="font-weight-normal mb-4 mb-md-0">Administración de facturas</h3>

            @*<a asp-area="Identity" asp-page="/Account/Register" id="btnCrear" class="btn btn-primary text-white"><i class="fa fa-plus"></i> Agregar nuevo usuario</a>*@

        </nav>


        <div id="my-listing_wrapper" class="dataTables_wrapper no-footer">
            <table id="tblFactura" class="  cell-border  table-data-default dataTable no-footer dtr-inline" style="width: 100%;" role="grid">
                <thead>
                    <tr class="table-row-bg-white" role="row">
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views"># Factura</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Usuario (Cliente)</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Subscripción</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">NoAutorizado</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Fecha pago</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Factura pagada</th>
                        <th rowspan="1" colspan="1" style="width: 10px;" aria-label="Views">Factura Enviada</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
            @*<div class="dataTables_paginate paging_simple_numbers" id="my-listing_paginate">
                    <a class="paginate_button previous disabled" aria-controls="my-listing" data-dt-idx="0" tabindex="0" id="my-listing_previous">Prev</a><span><a class="paginate_button current" aria-controls="my-listing" data-dt-idx="1" tabindex="0">1</a></span><a class="paginate_button next disabled" aria-controls="my-listing" data-dt-idx="2" tabindex="0" id="my-listing_next">Next</a>
                </div>*@
        </div>

    </div>
</section>

@section scripts{
    <script src="~/js/Handlers/facturasHandler.js"></script>
}

AppDirectorioWeb/AppDirectorioWeb/Areas/Ventas/Views/Facturacion/UpInvoice.cshtml
@model Models.ViewModels.FacturaViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = "Detalle Factura";
}

<section class="py-7 py-md-10 bg-light height100vh">
    <div class="container">
        <div class="border p-6 p-lg-9 bg-white">
            <div class="row">
                <div class="col-md-6 col-xs-12 pr-md-6 pr-lg-9">
                    <form asp-action="UpInvoice" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                       
                        <input asp-for="IdPlan" type="hidden">
                        <input asp-for="UserId" type="hidden">
                        <h2 class="h3 mb-6">@title</h2>
                        <div class="form-group mb-6">
                            <label asp-for="IdFactura"></label>
                            <input asp-for="IdFactura" type="text" class="form-control border" readonly>
                            <span asp-validation-for="IdFactura" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-6">
                            <label asp-for="User"></label>
                            <input asp-for="User" type="text" class="form-control border" readonly>
                            <span asp-validation-for="User" class="text-danger"></span>
                        </div>


                        <div class="form-group mb-6">
                            <label asp-for="PlanSuscripcion"></label>
                            <input asp-for="PlanSuscripcion" type="text" class="form-control border" readonly>
                            <span asp-validation-for="PlanSuscripcion" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-6">
                            <label asp-for="NoAutorizacion"></label>
                            <input asp-for="NoAutorizacion" type="text" class="form-control border">
                            <span asp-validation-for="NoAutorizacion" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-0">


                            <button type="submit" class="btn btn-primary text-uppercase py-2 px-4">Actualizar</button>

                            <a asp-area="Ventas" asp-action="Index" asp-controller="Facturacion" class="btn btn-warning text-white text-uppercase py-2 px-4">Regresar</a>
                        </div>

                        <hr class="my-7 d-md-none">
                    </form>
                </div>


            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}